import { ModelDesigner } from "../types/enums/ModelDesignerEnum";
import { OrderStatus } from "../types/enums/OrderStatusEnum";
import { OrderType } from "../types/enums/OrderTypeEnum";
import { LockReason } from "../types/enums/LockReasonEnum";
import { Order } from "../types/order";
export const dummyOrders: Order[] = [
  {
    oid: 12845,
    statusLeft: OrderStatus.ReadyForPackaging,
    statusRight: OrderStatus.ReadyForPackaging,
    status: "",
    type: OrderType.Sample,
    lock: LockReason.ModelNotReleased,
    customer: "Peter Maffeï",
    daysSinceOrder: 5,
    model: ModelDesigner.Nami,
    designer: ModelDesigner.FinnRushTaylor,
  },
  {
    oid: 12345,
    statusLeft: OrderStatus.Drying,
    statusRight: OrderStatus.ReadyForPackaging,
    status: "",
    type: OrderType.Sample,
    lock: LockReason.AddressIssue,
    customer: "Peter Orloff",
    daysSinceOrder: 5,
    model: ModelDesigner.Nami,
    designer: ModelDesigner.FinnRushTaylor,
  },
  {
    oid: 12584,
    statusLeft: OrderStatus.QC,
    statusRight: OrderStatus.ReadyForPackaging,
    status: "",
    type: OrderType.Sample,
    lock: "",
    customer: "Peter Pretel",
    daysSinceOrder: 5,
    model: ModelDesigner.Nami,
    designer: ModelDesigner.FinnRushTaylor,
  },
  {
    oid: 12700,
    statusLeft: OrderStatus.Delivered,
    statusRight: OrderStatus.Delivered,
    status: "",
    type: OrderType.Order,
    lock: "",
    customer: "Peter",
    daysSinceOrder: 3,
    model: ModelDesigner.Neptune,
    designer: ModelDesigner.Neptune,
  },
  {
    oid: 12222,
    statusLeft: OrderStatus.Printing,
    statusRight: OrderStatus.Printing,
    status: "",
    type: OrderType.Seeding,
    lock: LockReason.GCodeOutdated,
    customer: "Peter Maffeï",
    daysSinceOrder: 7,
    model: ModelDesigner.Lotus,
    designer: ModelDesigner.Lotus,
  },
  {
    oid: 12223,
    statusLeft: OrderStatus.OpenOrder,
    statusRight: OrderStatus.OpenOrder,
    status: "",
    type: OrderType.Order,
    lock: "",
    customer: "Peter Pretel",
    daysSinceOrder: 1,
    model: ModelDesigner.Mabuia,
    designer: ModelDesigner.Mabuia,
  },
  {
    oid: 12224,
    statusLeft: OrderStatus.QC,
    statusRight: OrderStatus.QC,
    status: "",
    type: OrderType.Sample,
    lock: "",
    customer: "Peter Maffeï",
    daysSinceOrder: 12,
    model: ModelDesigner.Nami,
    designer: ModelDesigner.FinnRushTaylor,
  },
  {
    oid: 12225,
    statusLeft: OrderStatus.Printing,
    statusRight: OrderStatus.Printing,
    status: "",
    type: OrderType.Order,
    lock: LockReason.Seeding,
    customer: "Peter Orloff",
    daysSinceOrder: 2,
    model: ModelDesigner.Neptune,
    designer: ModelDesigner.Neptune,
  },
  {
    oid: 12226,
    statusLeft: OrderStatus.Drying,
    statusRight: OrderStatus.Drying,
    status: "",
    type: OrderType.B2C,
    lock: "",
    customer: "Peter",
    daysSinceOrder: 6,
    model: ModelDesigner.Lotus,
    designer: ModelDesigner.Lotus,
  },
  {
    oid: 12227,
    statusLeft: OrderStatus.OpenOrder,
    statusRight: OrderStatus.OpenOrder,
    status: "",
    type: OrderType.Sample,
    lock: LockReason.ModelNotReleased,
    customer: "Peter Pretel",
    daysSinceOrder: 15,
    model: ModelDesigner.Mabuia,
    designer: ModelDesigner.Mabuia,
  },
  {
    oid: 12228,
    statusLeft: OrderStatus.QC,
    statusRight: OrderStatus.QC,
    status: "",
    type: OrderType.Sample,
    lock: "",
    customer: "Peter Maffeï",
    daysSinceOrder: 4,
    model: ModelDesigner.Nami,
    designer: ModelDesigner.FinnRushTaylor,
  },
  {
    oid: 12229,
    statusLeft: OrderStatus.Delivered,
    statusRight: OrderStatus.Delivered,
    status: "",
    type: OrderType.Order,
    lock: "",
    customer: "Peter Orloff",
    daysSinceOrder: 20,
    model: ModelDesigner.Neptune,
    designer: ModelDesigner.Neptune,
  },
  {
    oid: 12230,
    statusLeft: OrderStatus.Printing,
    statusRight: OrderStatus.Printing,
    status: "",
    type: OrderType.Sample,
    lock: LockReason.AddressIssue,
    customer: "Peter Pretel",
    daysSinceOrder: 10,
    model: ModelDesigner.Lotus,
    designer: ModelDesigner.Lotus,
  },
  {
    oid: 12231,
    statusLeft: OrderStatus.Drying,
    statusRight: OrderStatus.Drying,
    status: "",
    type: OrderType.Sample,
    lock: "",
    customer: "Peter Maffeï",
    daysSinceOrder: 3,
    model: ModelDesigner.Mabuia,
    designer: ModelDesigner.Mabuia,
  },
  {
    oid: 12232,
    statusLeft: OrderStatus.ReadyForPackaging,
    statusRight: OrderStatus.ReadyForPackaging,
    status: "",
    type: OrderType.Sample,
    lock: "",
    customer: "Peter",
    daysSinceOrder: 9,
    model: ModelDesigner.Nami,
    designer: ModelDesigner.FinnRushTaylor,
  },
  {
    oid: 12233,
    statusLeft: OrderStatus.QC,
    statusRight: OrderStatus.QC,
    status: "",
    type: OrderType.Order,
    lock: LockReason.ModelNotReleased,
    customer: "Peter Orloff",
    daysSinceOrder: 14,
    model: ModelDesigner.Neptune,
    designer: ModelDesigner.Neptune,
  },
  {
    oid: 12234,
    statusLeft: OrderStatus.Delivered,
    statusRight: OrderStatus.Delivered,
    status: "",
    type: OrderType.Order,
    lock: "",
    customer: "Peter Pretel",
    daysSinceOrder: 22,
    model: ModelDesigner.Mabuia,
    designer: ModelDesigner.Mabuia,
  },
  {
    oid: 12235,
    statusLeft: OrderStatus.OpenOrder,
    statusRight: OrderStatus.OpenOrder,
    status: "",
    type: OrderType.Order,
    lock: "",
    customer: "Peter",
    daysSinceOrder: 13,
    model: ModelDesigner.Mabuia,
    designer: ModelDesigner.Mabuia,
  },
  {
    oid: 12236,
    statusLeft: OrderStatus.Printing,
    statusRight: OrderStatus.Printing,
    status: "",
    type: OrderType.B2C,
    lock: "",
    customer: "Peter Orloff",
    daysSinceOrder: 11,
    model: ModelDesigner.Nami,
    designer: ModelDesigner.FinnRushTaylor,
  },
  {
    oid: 12237,
    statusLeft: OrderStatus.Drying,
    statusRight: OrderStatus.Drying,
    status: "",
    type: OrderType.Seeding,
    lock: "",
    customer: "Peter Pretel",
    daysSinceOrder: 19,
    model: ModelDesigner.Neptune,
    designer: ModelDesigner.Neptune,
  },
  {
    oid: 12238,
    statusLeft: OrderStatus.QC,
    statusRight: OrderStatus.QC,
    status: "",
    type: OrderType.Order,
    lock: "",
    customer: "Peter",
    daysSinceOrder: 18,
    model: ModelDesigner.Lotus,
    designer: ModelDesigner.Lotus,
  },
  {
    oid: 12239,
    statusLeft: OrderStatus.Delivered,
    statusRight: OrderStatus.Delivered,
    status: "",
    type: OrderType.Sample,
    lock: "",
    customer: "Peter Maffeï",
    daysSinceOrder: 13,
    model: ModelDesigner.Mabuia,
    designer: ModelDesigner.Mabuia,
  },
  {
    oid: 12240,
    statusLeft: OrderStatus.Printing,
    statusRight: OrderStatus.Printing,
    status: "",
    type: OrderType.Sample,
    lock: LockReason.Seeding,
    customer: "Peter Orloff",
    daysSinceOrder: 16,
    model: ModelDesigner.Nami,
    designer: ModelDesigner.FinnRushTaylor,
  },
  {
    oid: 12241,
    statusLeft: OrderStatus.Drying,
    statusRight: OrderStatus.Drying,
    status: "",
    type: OrderType.Sample,
    lock: LockReason.AddressIssue,
    customer: "Peter Pretel",
    daysSinceOrder: 17,
    model: ModelDesigner.Neptune,
    designer: ModelDesigner.Neptune,
  },
  {
    oid: 12242,
    statusLeft: OrderStatus.QC,
    statusRight: OrderStatus.QC,
    status: "",
    type: OrderType.Order,
    lock: "",
    customer: "Peter Maffeï",
    daysSinceOrder: 21,
    model: ModelDesigner.Lotus,
    designer: ModelDesigner.Lotus,
  },
  {
    oid: 12243,
    statusLeft: OrderStatus.Delivered,
    statusRight: OrderStatus.Delivered,
    status: "",
    type: OrderType.Order,
    lock: "",
    customer: "Peter Pretel",
    daysSinceOrder: 22,
    model: ModelDesigner.Mabuia,
    designer: ModelDesigner.Mabuia,
  },
  {
    oid: 12244,
    statusLeft: OrderStatus.ReadyForPackaging,
    statusRight: OrderStatus.ReadyForPackaging,
    status: "",
    type: OrderType.Order,
    lock: "",
    customer: "Peter Pretel",
    daysSinceOrder: 23,
    model: ModelDesigner.Nami,
    designer: ModelDesigner.FinnRushTaylor,
  },
  {
    oid: 12245,
    statusLeft: OrderStatus.OpenOrder,
    statusRight: OrderStatus.OpenOrder,
    status: "",
    type: OrderType.Sample,
    lock: LockReason.GCodeOutdated,
    customer: "Peter Orloff",
    daysSinceOrder: 24,
    model: ModelDesigner.Neptune,
    designer: ModelDesigner.Neptune,
  },
  {
    oid: 12246,
    statusLeft: OrderStatus.Printing,
    statusRight: OrderStatus.Printing,
    status: "",
    type: OrderType.Sample,
    lock: "",
    customer: "Peter Maffeï",
    daysSinceOrder: 25,
    model: ModelDesigner.Lotus,
    designer: ModelDesigner.Lotus,
  },
];
